version: "3"
services:
  paymybuddy-backend:
    build: .
    container_name: paymybuddy
    environment:
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_DATASOURCE_URL: jdbc:mysql://paymybuddy-db:3306/db_paymybuddy
    ports:
      - "8080:8080"
    networks:
      - paymybuddy-network

  paymybuddy-db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: db_paymybuddy
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - paymybuddy-network

volumes:
  db_data:

networks:
  paymybuddy-network:
    driver: bridge
