apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret  # Nom du secret
type: Opaque
data:
  rootpassword: <base64_encoded_root_password>  # Le mot de passe root en base64
  username: <base64_encoded_username>  # Le nom d'utilisateur pour la base de données en base64
  password: <base64_encoded_password>  # Le mot de passe pour la base de données en base64
