apiVersion: v1
kind: Service
metadata:
  name: paymybuddy-backend
spec:
  type: NodePort
  selector:
    app: paymybuddy-backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30080
